# Advanced settings to configure the minutiae of DRBOT.
# You don't need to change these unless you want something specific.

# Dry run mode - if you want to test DRBOT without actually banning anyone or sending any modmail.
# It will log what it would have done instead of actually doing it.
# Will still modify DRBOT's own local data structures.
dry_run = true

# Log file name. Leave blank to turn off the logfile (not recommended).
log_file = "log.log"

# Log level (one of CRITICAL, ERROR, WARNING, INFO, DEBUG) to print to the console / save to the file.
console_log_level = "INFO"
file_log_level = "DEBUG"

# Optionally, DRBOT can save PRAW's logging output to a file.
# This details every request made to the reddit API.
# It's off by default, but you can turn it on by setting this to a filename (e.g. praw.log).
praw_log_file = ""

# DRBOT stores its data on an automatically-managed wiki page on your sub.
# You can change the name of the page here, or leave it blank if you want everything to be local (not recommended).
wiki_page = "drbot"

# DRBOT also makes periodic local backups just in case things go wrong.
# You can set the filename of the backup here, or leave it blank to turn this off.
local_backup_file = "backup.json"

# When modmailing you, truncate long comments to this many characters (or set to 0 to disable truncation).
modmail_truncate_len = 100

# By default, the bot will not try to ban mods or keep track of their points.
# You can force it to include mods by setting this to false.
# Note that this may cause permissions issues with your sub - mods can't always ban other mods.
exclude_mods = true

# Safe mode - do greedy safety checks instead of lazy ones
# e.g. check for comment re-approval and mod status on every comment instead of periodically/before banning
# Will significantly slow down the bot and increase the traffic from your bot to reddit
safe_mode = false
